### ISSUE TITLE
Crashes on load

### ISSUE THREAD

**Issue by rbtying** [adicu/Courses#230]
```
Exception in defer callback: TypeError: undefined is not a function
    at RouteController.extend.onBeforeAction (http://courses.adicu.com/34c904d99461f9ded1bae767dbd8be4ea0d413a1.js:34:1881)
    at e.runHooks (http://courses.adicu.com/34c904d99461f9ded1bae767dbd8be4ea0d413a1.js:14:10906)
    at http://courses.adicu.com/34c904d99461f9ded1bae767dbd8be4ea0d413a1.js:14:23829
    at http://courses.adicu.com/34c904d99461f9ded1bae767dbd8be4ea0d413a1.js:14:23131
    at r._compute (http://courses.adicu.com/34c904d99461f9ded1bae767dbd8be4ea0d413a1.js:2:6086)
    at new e.Computation (http://courses.adicu.com/34c904d99461f9ded1bae767dbd8be4ea0d413a1.js:2:5418)
    at Object.r.autorun (http://courses.adicu.com/34c904d99461f9ded1bae767dbd8be4ea0d413a1.js:2:7260)
    at http://courses.adicu.com/34c904d99461f9ded1bae767dbd8be4ea0d413a1.js:14:23789
    at http://courses.adicu.com/34c904d99461f9ded1bae767dbd8be4ea0d413a1.js:14:23131
    at r._compute (http://courses.adicu.com/34c904d99461f9ded1bae767dbd8be4ea0d413a1.js:2:6086) 
```

**Comment by natebrennand** [comment]
did you do a hard refresh? it seems to be working for me

**Comment by rbtying** [comment]
Still having issues -- tested in chrome / firefox on linux, chrome on windows. Try not being logged in?

Edit -- yup, if I force the /login route it starts working. Also, `Spring 2014'' is presumably`Spring 2015''?

**Comment by brishin** [comment]
Yep, repo'd. We don't have Spring 2015 data as of yet.

**Comment by brishin** [comment]
Lovely. This is only happening in production on minified js

**Comment by brishin** [comment]
I think that I solved the underlying issue a while back but didn't push updated code because of some other issue. Let me know if it's fixed now, and close if it is.

**Comment by rbtying** [comment]
Looks like it's fixed
